export const TYPE = {
  SET_ROLE: 'SET_ROLE',
  AUTH: 'AUTH',
  SET_EMAIL: 'SET_EMAIL',
  SET_PROFILE: 'SET_PROFILE',
  SET_LOADING: 'SET_LOADING',
  SET_CATEGORY: 'SET_CATEGORY',
  SET_NOTIFICATION: 'SET_NOTIFICATION'
};
